### PR TITLE
Fix compilation on MSVC.

### LINKED ISSUE #3: Compile failure on MSVC
MS Visual Studio 2008 (which is used for the default python.org Python 2.7 builds) fails to compile lz4 with the following error:

    src/python-lz4.c(131) : error C2143: syntax error : missing ';' before 'type'

This is because MSVC 2008 doesn't permit mixing declarations with code. The fix is simple, and a patch is forthcoming.

### PR DESCRIPTION
**Pull request by nneonneo**
MSVC 2008 forbids mixed declarations and code, so just declare actual_size
earlier.

This fixes #3.

### CODE REVIEW

**Comment by jonathanunderwood** [comment]
Thanks - I believe this is already fixed on the refactor branch - are you able to test that branch and confirm?

**Comment by jonathanunderwood** [comment]
I've now merged the refactor branch back into master - so please test that branch.

**Comment by nneonneo** [comment]
New fix for new issue that cropped up in the refactor. Extension compiles fine on Windows after applying this patch.

File: lz4/frame/_frame.c [hunk 1]
```diff
@@ -171,12 +170,13 @@ py_lz4f_makePrefs (PyObject * Py_UNUSED (self), PyObject * args,
...
-  };
-  prefs->frameInfo = frameInfo;
+    LZ4F_frameInfo_t frameInfo = {
+      blkID, blkMode, chkSumFlag, 0, 0,
+      {0, 0}
+    };
+    prefs->frameInfo = frameInfo;
+  }
   prefs->autoFlush = autoFlush;
   result = PyCapsule_New (prefs, NULL, NULL);
```
Comment (jonathanunderwood) [inline lz4/frame/_frame.c]: This troubles me: the compound literal (which, actually I hate to see used and welcome expunging of!) assured static storage for frameInfo, so no problem with it persisting outside the function scope. It seems to me the alternative you've got here makes no such guarantee.

I think a better fix would be to allocate frameInfo explicitly (with a malloc).

Also, we should be checking the return value of calloc for prefs - I've been adding a lot of those to the frame code, but this is one I've missed.

**Comment by nneonneo** [comment]
This doesn't make sense to me. `frameInfo` is a structure - assigning it copies all the fields. It is *exactly* identical to the previous solution which used a compound literal. Compound literals, to my knowledge, do not assure static storage - they are literals and have no storage.

**Comment by jonathanunderwood** [comment]
Yes... Sunday morning, no coffee. You're right, of course, as to the equivalence. Literals do have storage, though (not that it's relevant or germaine here).

"The unnamed object to which the compound literal evaluates has static storage duration if the compound literal occurs at file scope and automatic storage duration if the compound literal occurs at block scope (in which case the object's lifetime ends at the end of the enclosing block)." 
From: http://en.cppreference.com/w/c/language/compound_literal
